# Generated by Django 6.0.7 on 2026-07-09 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('telefono', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'academia',
            },
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(max_length=25)),
                ('calle_principal', models.CharField(max_length=50)),
                ('calle_secundaria', models.CharField(max_length=50)),
                ('numero_casa', models.CharField(max_length=10)),
                ('referencia', models.TextField()),
            ],
            options={
                'verbose_name': 'Dirección',
                'verbose_name_plural': 'Direcciones',
                'db_table': 'direccion',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('academia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='gestion_academica.academia')),
            ],
            options={
                'db_table': 'curso',
            },
        ),
        migrations.AddField(
            model_name='academia',
            name='direccion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='academia', to='gestion_academica.direccion'),
        ),
        migrations.CreateModel(
            name='Paralelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('dias_clase', models.CharField(max_length=50)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('cupo_max', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paralelos', to='gestion_academica.curso')),
            ],
            options={
                'db_table': 'paralelo',
            },
        ),
    ]
