# Generated by Django 6.0.7 on 2026-07-12 23:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_academica', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persona', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='matricula',
            name='calificacion_final',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calificacion_final', to='gestion_academica.calificacionfinal'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='comprobante_pago',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='matricula', to='gestion_academica.comprobantepago'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='matricula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='gestion_academica.matricula'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paralelo',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paralelos', to='gestion_academica.curso'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='paralelo_matricula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='gestion_academica.paralelo'),
        ),
        migrations.AddField(
            model_name='paralelo',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paralelos', to='gestion_academica.docente'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='gestion_academica.estudiante'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='representante_legal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes', to='gestion_academica.representante'),
        ),
    ]
