# Generated by Django 6.0.7 on 2026-07-23 01:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academica', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('DESACTIVADO', 'Desactivado'), ('CERRADO', 'Cerrado')], default='ACTIVO', max_length=15),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='numero_casa',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='referencia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='representante_legal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes', to='gestion_academica.representante'),
        ),
        migrations.AlterField(
            model_name='paralelo',
            name='cupo_max',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='paralelo',
            name='dias_clase',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='paralelo',
            name='docente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paralelos', to='gestion_academica.docente'),
        ),
        migrations.AlterField(
            model_name='paralelo',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('DESACTIVADO', 'Desactivado')], default='ACTIVO', max_length=15),
        ),
    ]
