# Generated by Django 6.0.7 on 2026-07-22 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academica', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='representante_legal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes', to='gestion_academica.representante'),
        ),
    ]
