# Generated by Django 6.0.7 on 2026-07-23 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academica', '0004_curso_descripcion_curso_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('DESACTIVADO', 'Desactivado'), ('CERRADO', 'Cerrado')], default='ACTIVO', max_length=15),
        ),
        migrations.AddField(
            model_name='matricula',
            name='comentario',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='paralelo',
            name='dias_clase',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='paralelo',
            name='docente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paralelos', to='gestion_academica.docente'),
        ),
        migrations.AlterField(
            model_name='paralelo',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('DESACTIVADO', 'Desactivado')], default='ACTIVO', max_length=15),
        ),
    ]
