# Generated by Django 6.0.7 on 2026-07-23 22:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academica', '0005_curso_estado_matricula_comentario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='fecha_baja',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='motivo_baja',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='comprobantepago',
            name='tipo_archivo',
            field=models.FileField(upload_to='comprobantes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png'])]),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobada', 'Aprobada'), ('Rechazada', 'Rechazada'), ('Finalizada', 'Finalizada'), ('Cancelada', 'Cancelada')], default='Pendiente', max_length=20),
        ),
    ]
