# Generated by Django 6.0.7 on 2026-07-23 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academica', '0006_estudiante_fecha_baja_estudiante_motivo_baja_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacionfinal',
            name='nota_final',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
