# Generated by Django 6.0.7 on 2026-07-23 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academica', '0007_alter_calificacionfinal_nota_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
