# Generated by Django 6.0.7 on 2026-07-23 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academica', '0008_alter_notificacion_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobantepago',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
