# Generated by Django 6.0.7 on 2026-07-27 13:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academica', '0009_alter_comprobantepago_monto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobantepago',
            name='tipo_archivo',
            field=models.FileField(blank=True, null=True, upload_to='comprobantes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png'])]),
        ),
    ]
